import type { EventRecord, FrontierEntry, InformationItem, Service, TrendProject } from "./types";

export const siteStatus = {
  updated: "2026-07-22T18:00:00+08:00",
  sources: 128,
  season: "2026 夏季赛",
  seasonState: "开放报名",
  settlement: "2026.09.30",
};

export const events: EventRecord[] = [
  {
    slug: "open-agent-runtime-release",
    record: "VLT/EVT/2026/00731",
    category: "模型与产品",
    title: "开放式 Agent 运行时发布长任务状态恢复能力",
    judgment: "长任务恢复正成为生产级门槛",
    originalTitle: "Open agent runtime adds durable recovery for long-running tasks",
    summary: "开放式 Agent 运行时把执行记录、工具结果和人工确认点分别持久化，使被网络故障或进程退出中断的任务可以从最近可信节点继续，而不是重新执行全部步骤。[2]\n\n独立测试确认，恢复是否可靠取决于外部工具状态能否同步保存；已经产生外部副作用的步骤仍需要显式核对，不能只靠重放模型上下文。[3]\n\n这使长任务运行时的竞争重点从单次推理速度转向执行连续性。对跨越数小时的自动化而言，可恢复、可核对和可接管正在成为进入生产环境的共同门槛。[1]",
    significance: "对一人公司而言，Agent 是否能恢复，比单次推理速度更接近真实生产力。它决定了自动化流程能否跨越数小时甚至数天稳定运行。",
    entities: ["Agent Runtime", "Long-running Tasks", "Workflow"],
    firstSeen: "2026.07.21 09:10",
    updated: "2026-07-22T11:20:00+08:00",
    sources: [
      { name: "项目官方博客", url: "https://example.com/source/runtime", publishedAt: "2026.07.21 09:00" },
      { name: "GitHub Release", url: "https://github.com/example/runtime", publishedAt: "2026.07.21 10:18" },
    ],
    timeline: [
      { time: "09:00", text: "官方博客发布架构说明。" },
      { time: "10:18", text: "GitHub 同步发布可测试版本。" },
      { time: "13:42", text: "维护者补充迁移和回滚说明。" },
    ],
  },
  {
    slug: "small-model-tool-use",
    record: "VLT/EVT/2026/00728",
    category: "研究与能力",
    title: "小模型工具调用研究把重点从准确率转向恢复成本",
    judgment: "恢复成本比单次成功更接近实用性",
    originalTitle: "Tool-use evaluation shifts toward recovery cost for smaller models",
    summary: "新的评测把失败后的恢复步数、额外工具调用和任务重放成本纳入指标，不再只用最终是否完成任务判断小模型的工具能力。[2]\n\n相关测试显示，一些低价模型在首次调用中的成本更低，却因重试、人工接管和状态修复产生更高的总任务成本。[1][3]\n\n这改变了模型路由的优化目标：系统需要计算从开始到可信交付的完整成本，而不是比较单次 Token 价格。恢复能力因此成为衡量小模型实用性的核心维度。",
    significance: "这更符合超级个体对成本、延迟和可维护性的真实约束，也为模型路由提供了更实用的评价维度。",
    entities: ["Small Models", "Tool Use", "Evaluation"],
    firstSeen: "2026.07.20 18:20",
    updated: "2026-07-22T07:30:00+08:00",
    sources: [
      { name: "研究预印本", url: "https://example.com/source/paper", publishedAt: "2026.07.20 18:00" },
    ],
    timeline: [
      { time: "07.20 18:00", text: "论文与评测代码同步公开。" },
      { time: "07.21 08:14", text: "作者补充不同工具数量下的消融结果。" },
    ],
  },
  {
    slug: "founder-context-interview",
    record: "VLT/EVT/2026/00724",
    category: "公司与市场",
    title: "一人公司真正稀缺的不是工具，而是连续上下文",
    judgment: "连续上下文正在取代工具数量优势",
    originalTitle: "The scarce resource in a one-person company is continuous context",
    summary: "多位个人经营者把返工归因于客户决策、代码变化和日常运营之间的上下文断裂，而不是单个工具缺少功能。[2][3]\n\n工具越多，跨系统复制信息和重新解释历史决定的成本越高。案例研究显示，先把输入、验收和异常处理固定下来，人工接管次数才会下降。[1]\n\n对一人公司而言，稀缺能力正在从“拥有多少工具”转向“能否让关键上下文持续存在”。产品若不能保存决策来源和交接边界，新增自动化只会更快地放大信息损耗。",
    significance: "这解释了为什么大量自动化最终仍退化为人工复制粘贴，也指向 Vault2077 应关注的基础设施方向。",
    entities: ["Solo Founder", "Context", "Operations"],
    firstSeen: "2026.07.20 12:30",
    updated: "2026-07-21T15:40:00+08:00",
    sources: [
      { name: "公开访谈", url: "https://example.com/source/interview", publishedAt: "2026.07.20 12:00" },
    ],
    timeline: [{ time: "12:00", text: "访谈节目发布。" }],
  },
  {
    slug: "agent-memory-podcast",
    record: "VLT/EVT/2026/00719",
    category: "研究与能力",
    title: "当 Agent 拥有长期记忆，产品边界会发生什么变化",
    judgment: "记忆能力必须与用户控制权同时设计",
    originalTitle: "What changes when agents retain long-term memory?",
    summary: "长期记忆产品开始把来源查看、错误修订和条目删除变成显式用户能力，而不是只提供不可见的后台检索。[1]\n\n安全分析指出，记忆会跨任务持续改变后续 Agent 能看到的信息和采取的行动；错误一旦进入记忆层，影响会在不同工作流中累积。[2]\n\n因此，长期记忆不是单纯的向量库功能，而是一套持续权限系统。产品必须同时设计保留期限、来源追溯和用户控制权，个性化收益才不会以不可控的错误积累为代价。[3]",
    significance: "长期记忆不是简单的向量库功能，而是权限、可解释性与产品责任的组合问题。",
    entities: ["Agent Memory", "Privacy", "Product Design"],
    firstSeen: "2026.07.19 21:00",
    updated: "2026-07-21T12:10:00+08:00",
    sources: [
      { name: "播客节目页", url: "https://example.com/source/podcast", publishedAt: "2026.07.19 21:00" },
      { name: "节目文字稿", url: "https://example.com/source/transcript", publishedAt: "2026.07.20 09:05" },
    ],
    timeline: [
      { time: "07.19 21:00", text: "节目上线。" },
      { time: "07.20 09:05", text: "完整文字稿发布。" },
    ],
  },
  {
    slug: "inference-price-update",
    record: "VLT/EVT/2026/00715",
    category: "公司与市场",
    title: "推理服务调整批处理价格与缓存计费规则",
    judgment: "计费细节开始直接影响自动化毛利",
    originalTitle: "Inference platform updates batch and cache pricing",
    summary: "推理平台降低了批处理输入价格，同时把长时间缓存保留调整为分段计费，两项规则在同一轮价格更新中生效。[2]\n\n成本测算显示，集中执行的夜间批任务获得更明显降幅，高频交互工作流则可能因缓存保留时间增加而承担更高费用。[3]\n\n这意味着模型单价已经不足以判断自动化毛利。调用频率、缓存生命周期和任务编排方式会产生相反的成本结果，小型开发者需要按真实工作流重新计算单位经济性。[1]",
    significance: "一人公司常把多个自动化任务集中到少数模型供应商，计费细节变化可能直接改变产品毛利。",
    entities: ["Inference", "Pricing", "Caching"],
    firstSeen: "2026.07.19 15:10",
    updated: "2026-07-20T17:40:00+08:00",
    sources: [
      { name: "官方定价页", url: "https://example.com/source/pricing", publishedAt: "2026.07.19 15:00" },
    ],
    timeline: [
      { time: "15:00", text: "新定价规则生效。" },
      { time: "18:22", text: "官方补充缓存计费示例。" },
    ],
  },
  {
    slug: "mcp-audit-patterns",
    record: "VLT/EVT/2026/00708",
    category: "政策与安全",
    title: "MCP 服务审计开始形成可复用的最小检查框架",
    judgment: "工具连接正在形成默认安全基线",
    originalTitle: "A minimal audit framework emerges for MCP servers",
    summary: "社区发布的最小检查清单把权限声明、输入边界、外部请求、密钥处理和依赖来源统一纳入 MCP 服务安装前审计。[1]\n\n对公开服务的实测表明，最常见的缺口不是已经确认的恶意代码，而是没有说明运行时会连接哪些外部地址，用户难以判断数据边界。[2]\n\n当工具连接成为 Agent 的基础能力，安装前审计正在从高级安全选项变成默认环节。长期记忆等持续状态还会扩大权限影响范围，因此检查框架需要覆盖工具运行后的数据保留。[3]",
    significance: "当工具连接成为 Agent 基础能力，安装前审计会像依赖漏洞扫描一样成为默认环节。",
    entities: ["MCP", "Security", "Audit"],
    firstSeen: "2026.07.18 16:40",
    updated: "2026-07-21T10:50:00+08:00",
    sources: [
      { name: "维护者文章", url: "https://example.com/source/audit", publishedAt: "2026.07.18 16:40" },
      { name: "规范仓库", url: "https://github.com/example/audit", publishedAt: "2026.07.19 11:12" },
    ],
    timeline: [
      { time: "07.18 16:40", text: "检查框架首次公开。" },
      { time: "07.19 11:12", text: "规则文件和示例仓库开放。" },
    ],
  },
  {
    slug: "open-voice-stack",
    record: "VLT/EVT/2026/00702",
    category: "开源与生态",
    title: "开源语音栈新增端侧流式合成与中断恢复",
    judgment: "端侧语音正接近可组合生产模块",
    originalTitle: "Open voice stack adds on-device streaming and interruption recovery",
    summary: "开源语音栈的新版本降低了端侧合成的首帧等待，并允许对话被打断后从最近的语义边界恢复输出。[1]\n\n多设备测试确认，中端硬件上的首帧延迟明显下降，但长文本仍会增加内存压力；恢复机制也需要保存外部工具和音频状态。[2]\n\n端侧语音由单次演示走向可组合模块，关键不再只是生成音质，而是流式延迟、中断恢复和设备资源能否同时满足真实工作流。通用安全检查也开始覆盖这类带外部依赖的组件。[3]",
    significance: "端侧语音能力正在从演示走向可组合模块，为小团队减少实时交互基础设施成本。",
    entities: ["Voice", "On-device", "Streaming"],
    firstSeen: "2026.07.18 10:00",
    updated: "2026-07-20T13:30:00+08:00",
    sources: [
      { name: "项目公告", url: "https://example.com/source/voice", publishedAt: "2026.07.18 10:00" },
    ],
    timeline: [
      { time: "10:00", text: "版本与性能报告发布。" },
      { time: "14:25", text: "维护者更新兼容设备列表。" },
    ],
  },
  {
    slug: "solo-company-ops-stack",
    record: "VLT/EVT/2026/00698",
    category: "公司与市场",
    title: "超级个体的中后台应先标准化，再谈全面自动化",
    judgment: "标准化仍是自动化之前的必要步骤",
    originalTitle: "Standardize solo-company operations before automating everything",
    summary: "运营实践把合同、财税、客户交付和内容发布拆成输入、处理边界、验收标准与异常处置，主张先形成稳定清单再接入 Agent。[1]\n\n案例研究显示，完成清单化后，自动化流程需要人工接管的次数下降；没有固定边界的流程则会更快地产生返工和责任不清。[2]\n\n这说明全面自动化不是起点。对一人公司而言，标准化先把专业经验变成可验证的运行接口，随后才能判断哪些步骤适合交给模型、哪些仍需人工确认。[3]",
    significance: "这与 OPC 服务台的产品方法一致：先把专业经验封装成边界明确的服务，再逐步增加自动化。",
    entities: ["OPC", "Operations", "Automation"],
    firstSeen: "2026.07.17 19:20",
    updated: "2026-07-21T12:10:00+08:00",
    sources: [
      { name: "创始人公开文章", url: "https://example.com/source/ops", publishedAt: "2026.07.17 19:20" },
    ],
    timeline: [{ time: "19:20", text: "文章发布。" }],
  },
  {
    slug: "auditable-browser-agents",
    record: "VLT/EVT/2026/00694",
    category: "模型与产品",
    title: "浏览器 Agent 开始进入可审计执行阶段",
    judgment: "执行记录正在取代演示成功率",
    summary: "多家工具提供方开始把浏览器 Agent 的页面状态、关键点击和工具返回写入可回放记录。[1]\n\n独立测试显示，记录完整性比单次任务成功率更能暴露流程中的脆弱环节。[2]\n\n这意味着浏览器自动化的竞争重点正在从“能否完成”转向“失败后能否解释、恢复和追责”。[3]",
    significance: "执行记录正在取代演示成功率",
    entities: ["Browser Agent", "Audit Log", "Recovery"],
    firstSeen: "2026-07-17T08:40:00+08:00",
    updated: "2026-07-22T09:00:00+08:00",
    sources: [],
    timeline: [],
  },
  {
    slug: "open-model-license-policy",
    record: "VLT/EVT/2026/00690",
    category: "政策与安全",
    title: "开源模型许可证争议进入政策讨论",
    judgment: "模型治理正在成为市场变量",
    summary: "新的行业讨论把模型权重开放、训练数据披露和商业使用限制放在同一个许可框架中审视。[1]\n\n法律评论指出，传统软件许可证无法完整覆盖模型训练、微调和再分发形成的责任链。[2]\n\n对于小型开发者，许可证是否清楚将直接影响部署选择、融资尽调和后续产品分发。[3]",
    significance: "模型治理正在成为市场变量",
    entities: ["Open Model", "License", "Policy"],
    firstSeen: "2026-07-16T16:20:00+08:00",
    updated: "2026-07-20T17:40:00+08:00",
    sources: [],
    timeline: [],
  },
];

export const informationItems: InformationItem[] = [
  {
    slug: "durable-agent-runtime-release",
    translatedTitle: "开放运行时发布可恢复的长任务执行记录",
    originalTitle: "Open runtime ships durable execution records for long-running agents",
    summary: "长任务可从可信检查点继续执行",
    translatedContent: "项目发布了持久化执行记录和可信检查点机制。任务中断后可以恢复工具结果、人工确认状态和未完成步骤。",
    originalContent: "The runtime now persists execution records, tool results and approval checkpoints so interrupted tasks can resume from the last trusted state.",
    originalLanguage: "en",
    sourceName: "项目官方博客",
    sourceRole: "官方",
    sourceUrl: "https://example.com/source/runtime-release",
    author: "Runtime Team",
    publishedAt: "2026-07-22T09:00:00+08:00",
    discoveredAt: "2026-07-22T12:00:00+08:00",
    eventSlugs: ["open-agent-runtime-release", "auditable-browser-agents"],
    primaryEventSlug: "open-agent-runtime-release",
    originalDisplay: "excerpt",
  },
  {
    slug: "agent-runtime-recovery-test",
    translatedTitle: "独立测试记录长任务中断后的恢复边界",
    originalTitle: "Testing where durable agents actually recover after interruption",
    summary: "恢复效果取决于工具状态是否持久化",
    translatedContent: "测试者在网络断开、工具超时和人工确认中断三种场景下重复运行任务，发现外部工具状态仍是主要失败点。",
    originalContent: "Recovery worked when tool state was persisted, but network timeouts and external side effects still required explicit reconciliation.",
    originalLanguage: "en",
    sourceName: "Agent Bench",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/runtime-test",
    author: "Mira Chen",
    publishedAt: "2026-07-22T11:20:00+08:00",
    discoveredAt: "2026-07-22T12:00:00+08:00",
    eventSlugs: ["open-agent-runtime-release"],
    primaryEventSlug: "open-agent-runtime-release",
    originalDisplay: "excerpt",
  },
  {
    slug: "small-model-recovery-paper",
    translatedTitle: "研究提出用恢复成本评估小模型工具调用",
    originalTitle: "Recovery cost is a better tool-use metric for small models",
    summary: "研究把失败后的额外调用纳入评测",
    translatedContent: "论文用恢复步数、额外调用次数和任务重放成本替代单一成功率，重新比较了多种小模型。",
    originalContent: "The study evaluates smaller models by recovery steps, additional tool calls and replay cost instead of final task completion alone.",
    originalLanguage: "en",
    sourceName: "研究预印本",
    sourceRole: "研究",
    sourceUrl: "https://example.com/source/recovery-paper",
    author: "Evaluation Lab",
    publishedAt: "2026-07-21T18:10:00+08:00",
    discoveredAt: "2026-07-22T00:00:00+08:00",
    eventSlugs: ["small-model-tool-use", "auditable-browser-agents"],
    primaryEventSlug: "small-model-tool-use",
    originalDisplay: "excerpt",
  },
  {
    slug: "small-model-routing-commentary",
    translatedTitle: "开发者讨论恢复成本对模型路由的影响",
    originalTitle: "What recovery-aware evaluation changes about model routing",
    summary: "低价模型的失败成本可能抵消价差",
    translatedContent: "评论指出，便宜模型若需要更多重试和人工接管，其总体任务成本可能高于更强模型。",
    originalContent: "A cheaper model can become the expensive choice once retries, human intervention and recovery latency are included.",
    originalLanguage: "en",
    sourceName: "Independent Systems",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/routing-commentary",
    author: "A. Patel",
    publishedAt: "2026-07-22T07:30:00+08:00",
    discoveredAt: "2026-07-22T12:00:00+08:00",
    eventSlugs: ["small-model-tool-use"],
    primaryEventSlug: "small-model-tool-use",
    originalDisplay: "excerpt",
  },
  {
    slug: "continuous-context-interview",
    translatedTitle: "创始人访谈强调一人公司的连续上下文",
    originalTitle: "Continuous context is the scarce resource in a one-person company",
    summary: "工具增加无法弥补上下文反复丢失",
    translatedContent: "受访者认为，客户、代码和经营决策之间的上下文连续性，比继续增加工具更影响个人公司的交付能力。",
    originalContent: "The limiting resource is not another tool but continuity across customer decisions, code changes and daily operations.",
    originalLanguage: "en",
    sourceName: "Builder Radio",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/context-interview",
    author: "Nora Hale",
    publishedAt: "2026-07-21T12:10:00+08:00",
    discoveredAt: "2026-07-21T18:00:00+08:00",
    eventSlugs: ["founder-context-interview", "agent-memory-podcast", "solo-company-ops-stack"],
    primaryEventSlug: "founder-context-interview",
    originalDisplay: "excerpt",
  },
  {
    slug: "solo-ops-context-report",
    translatedTitle: "调查显示个人团队频繁在工具切换中丢失决策",
    originalTitle: "Solo operators lose decisions between tools, not inside them",
    summary: "跨工具交接成为主要信息损耗点",
    translatedContent: "一项小型调查把返工主要归因于工具间交接，而不是单个工具缺少功能。",
    originalContent: "Respondents traced most rework to handoffs between tools rather than missing features inside any single product.",
    originalLanguage: "en",
    sourceName: "Solo Work Review",
    sourceRole: "研究",
    sourceUrl: "https://example.com/source/context-report",
    author: "Research Desk",
    publishedAt: "2026-07-21T15:40:00+08:00",
    discoveredAt: "2026-07-21T18:00:00+08:00",
    eventSlugs: ["founder-context-interview"],
    primaryEventSlug: "founder-context-interview",
    originalDisplay: "excerpt",
  },
  {
    slug: "agent-memory-controls",
    translatedTitle: "长期记忆接口新增查看、修订和删除能力",
    originalTitle: "Agent memory interface adds inspect, revise and delete controls",
    summary: "记忆能力开始绑定明确的用户控制权",
    translatedContent: "新接口允许用户查看记忆来源、修订错误记录并删除不应继续保留的条目。",
    originalContent: "Users can now inspect where a memory came from, revise incorrect records and delete entries that should no longer persist.",
    originalLanguage: "en",
    sourceName: "产品更新",
    sourceRole: "官方",
    sourceUrl: "https://example.com/source/memory-controls",
    author: "Memory Product Team",
    publishedAt: "2026-07-21T09:20:00+08:00",
    discoveredAt: "2026-07-21T12:00:00+08:00",
    eventSlugs: ["agent-memory-podcast"],
    primaryEventSlug: "agent-memory-podcast",
    originalDisplay: "excerpt",
  },
  {
    slug: "memory-permission-analysis",
    translatedTitle: "安全分析将长期记忆视为持续权限系统",
    originalTitle: "Long-term agent memory behaves like a persistent permission system",
    summary: "记忆错误会跨任务持续累积影响",
    translatedContent: "分析认为，长期记忆不仅是检索功能，还会持续改变后续任务中的可见信息和行动边界。",
    originalContent: "Long-term memory is not only retrieval; it continuously changes what later tasks can see and how they act.",
    originalLanguage: "en",
    sourceName: "Secure Agents",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/memory-permission",
    author: "Iris Wong",
    publishedAt: "2026-07-21T10:50:00+08:00",
    discoveredAt: "2026-07-21T12:00:00+08:00",
    eventSlugs: ["agent-memory-podcast", "mcp-audit-patterns"],
    primaryEventSlug: "agent-memory-podcast",
    originalDisplay: "excerpt",
  },
  {
    slug: "inference-pricing-update",
    translatedTitle: "推理平台更新批处理和长缓存计费规则",
    originalTitle: "Inference platform updates batch and long-cache pricing",
    summary: "批处理降价与缓存分段计费同时生效",
    translatedContent: "平台降低批处理输入价格，同时把长缓存保留调整为按时间段收费。",
    originalContent: "Batch input prices are lower, while long-lived cache retention is now billed in time-based segments.",
    originalLanguage: "en",
    sourceName: "官方定价页",
    sourceRole: "官方",
    sourceUrl: "https://example.com/source/pricing-update",
    author: "Pricing Team",
    publishedAt: "2026-07-20T15:00:00+08:00",
    discoveredAt: "2026-07-20T18:00:00+08:00",
    eventSlugs: ["inference-price-update"],
    primaryEventSlug: "inference-price-update",
    originalDisplay: "excerpt",
  },
  {
    slug: "inference-margin-analysis",
    translatedTitle: "成本分析比较高频工作流与夜间批任务",
    originalTitle: "New inference pricing splits interactive and overnight workload economics",
    summary: "不同调用结构开始产生相反成本结果",
    translatedContent: "测算显示，高频交互任务可能增加缓存成本，而集中执行的夜间批任务获得更明显降幅。",
    originalContent: "Interactive workloads may pay more for retained cache, while consolidated overnight batches capture most of the discount.",
    originalLanguage: "en",
    sourceName: "Compute Ledger",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/pricing-analysis",
    author: "Cost Lab",
    publishedAt: "2026-07-20T17:40:00+08:00",
    discoveredAt: "2026-07-20T18:00:00+08:00",
    eventSlugs: ["inference-price-update", "open-model-license-policy"],
    primaryEventSlug: "inference-price-update",
    originalDisplay: "excerpt",
  },
  {
    slug: "mcp-audit-checklist",
    translatedTitle: "社区发布 MCP 服务最小安全检查清单",
    originalTitle: "A minimal security checklist for MCP servers",
    summary: "权限、外部请求和密钥进入基础检查",
    translatedContent: "清单覆盖权限声明、输入边界、外部请求、密钥处理和依赖来源。",
    originalContent: "The checklist covers declared permissions, input boundaries, outbound requests, secret handling and dependency provenance.",
    originalLanguage: "en",
    sourceName: "规范仓库",
    sourceRole: "官方",
    sourceUrl: "https://github.com/example/mcp-audit",
    author: "MCP Audit Maintainers",
    publishedAt: "2026-07-20T11:10:00+08:00",
    discoveredAt: "2026-07-20T12:00:00+08:00",
    eventSlugs: ["mcp-audit-patterns"],
    primaryEventSlug: "mcp-audit-patterns",
    originalDisplay: "full",
  },
  {
    slug: "mcp-audit-field-test",
    translatedTitle: "实测发现多数 MCP 服务缺少外部请求说明",
    originalTitle: "Most tested MCP servers do not document outbound requests",
    summary: "外部请求披露成为最常见缺口",
    translatedContent: "对一组公开服务的检查显示，最常见的问题不是恶意代码，而是没有说明运行时会访问哪些外部地址。",
    originalContent: "The most common gap was not malicious code but missing documentation of which external endpoints the server contacts at runtime.",
    originalLanguage: "en",
    sourceName: "Protocol Test Lab",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/mcp-field-test",
    author: "Test Desk",
    publishedAt: "2026-07-20T13:30:00+08:00",
    discoveredAt: "2026-07-20T18:00:00+08:00",
    eventSlugs: ["mcp-audit-patterns", "open-voice-stack"],
    primaryEventSlug: "mcp-audit-patterns",
    originalDisplay: "excerpt",
  },
  {
    slug: "voice-stack-release",
    translatedTitle: "开源语音栈发布端侧流式合成和恢复功能",
    originalTitle: "Open voice stack ships on-device streaming and interruption recovery",
    summary: "语音任务可从语义边界恢复输出",
    translatedContent: "新版本降低首帧等待，并在对话被打断后从最近的语义边界恢复。",
    originalContent: "The release reduces time to first audio and resumes interrupted output from the nearest semantic boundary.",
    originalLanguage: "en",
    sourceName: "项目公告",
    sourceRole: "官方",
    sourceUrl: "https://example.com/source/voice-release",
    author: "Voice Foundry",
    publishedAt: "2026-07-19T10:00:00+08:00",
    discoveredAt: "2026-07-19T12:00:00+08:00",
    eventSlugs: ["open-voice-stack"],
    primaryEventSlug: "open-voice-stack",
    originalDisplay: "excerpt",
  },
  {
    slug: "voice-stack-device-test",
    translatedTitle: "设备测试验证端侧语音首帧延迟下降",
    originalTitle: "On-device voice test shows lower first-audio latency",
    summary: "中端设备的首帧等待明显下降",
    translatedContent: "测试在三类设备上比较新旧版本，确认中端设备首帧等待下降，但长文本仍会增加内存压力。",
    originalContent: "Across three device classes, first-audio latency improved on mid-range hardware, while long passages still increased memory pressure.",
    originalLanguage: "en",
    sourceName: "Edge Audio Review",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/voice-device-test",
    author: "Audio Bench",
    publishedAt: "2026-07-19T14:25:00+08:00",
    discoveredAt: "2026-07-19T18:00:00+08:00",
    eventSlugs: ["open-voice-stack", "open-agent-runtime-release"],
    primaryEventSlug: "open-voice-stack",
    originalDisplay: "excerpt",
  },
  {
    slug: "standardize-before-automation",
    translatedTitle: "运营文章主张先固定清单再引入全面自动化",
    originalTitle: "Standardize the operating checklist before automating the company",
    summary: "不稳定流程会被自动化更快放大",
    translatedContent: "文章以合同、财税和交付流程为例，说明不清晰的边界会让自动化更快地产生错误。",
    originalContent: "Across contracts, finance and delivery, automation amplifies unclear boundaries faster than it removes manual work.",
    originalLanguage: "en",
    sourceName: "Solo Operations",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/standardize-first",
    author: "Lena Ortiz",
    publishedAt: "2026-07-18T19:20:00+08:00",
    discoveredAt: "2026-07-19T00:00:00+08:00",
    eventSlugs: ["solo-company-ops-stack"],
    primaryEventSlug: "solo-company-ops-stack",
    originalDisplay: "excerpt",
  },
  {
    slug: "solo-ops-checklist-study",
    translatedTitle: "案例研究比较清单化前后的自动化返工率",
    originalTitle: "Checklist-first operations reduce automation rework",
    summary: "边界清单降低了人工接管次数",
    translatedContent: "案例记录显示，先明确输入、验收和异常处理后，自动化流程的人工接管次数明显减少。",
    originalContent: "Defining inputs, acceptance criteria and exception handling before automation reduced the number of human takeovers.",
    originalLanguage: "en",
    sourceName: "Operations Study",
    sourceRole: "研究",
    sourceUrl: "https://example.com/source/checklist-study",
    author: "Workflow Group",
    publishedAt: "2026-07-19T08:15:00+08:00",
    discoveredAt: "2026-07-19T12:00:00+08:00",
    eventSlugs: ["solo-company-ops-stack", "founder-context-interview"],
    primaryEventSlug: "solo-company-ops-stack",
    originalDisplay: "excerpt",
  },
  {
    slug: "browser-agent-audit-log",
    translatedTitle: "浏览器 Agent 新版本公开逐步执行记录",
    originalTitle: "Browser agent release exposes step-by-step execution logs",
    summary: "关键点击和页面状态可以被回放",
    translatedContent: "版本新增逐步日志，记录页面状态、关键点击、工具返回以及人工确认点。",
    originalContent: "The release records page state, consequential clicks, tool returns and approval checkpoints in a replayable log.",
    originalLanguage: "en",
    sourceName: "产品发布说明",
    sourceRole: "官方",
    sourceUrl: "https://example.com/source/browser-audit-log",
    author: "Browser Agent Team",
    publishedAt: "2026-07-18T08:40:00+08:00",
    discoveredAt: "2026-07-18T12:00:00+08:00",
    eventSlugs: ["auditable-browser-agents"],
    primaryEventSlug: "auditable-browser-agents",
    originalDisplay: "excerpt",
  },
  {
    slug: "browser-agent-replay-test",
    translatedTitle: "回放测试暴露浏览器自动化的隐性失败步骤",
    originalTitle: "Replay testing reveals hidden failure steps in browser automation",
    summary: "可回放记录让失败原因更容易定位",
    translatedContent: "独立测试通过回放记录定位到页面重排和确认弹窗造成的隐性失败。",
    originalContent: "Replay logs exposed silent failures caused by layout shifts and confirmation dialogs that headline success rates had hidden.",
    originalLanguage: "en",
    sourceName: "Automation Review",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/browser-replay-test",
    author: "QA Desk",
    publishedAt: "2026-07-18T15:10:00+08:00",
    discoveredAt: "2026-07-18T18:00:00+08:00",
    eventSlugs: ["auditable-browser-agents", "small-model-tool-use"],
    primaryEventSlug: "auditable-browser-agents",
    originalDisplay: "excerpt",
  },
  {
    slug: "open-model-license-roundtable",
    translatedTitle: "政策圆桌讨论模型权重开放与商业限制",
    originalTitle: "Policy roundtable examines open weights and commercial restrictions",
    summary: "模型开放程度缺少统一许可语言",
    translatedContent: "讨论把权重访问、训练数据披露、微调和再分发分别处理，指出“开放模型”仍缺少统一定义。",
    originalContent: "The roundtable separated weight access, data disclosure, fine-tuning and redistribution, finding no shared definition of an open model.",
    originalLanguage: "en",
    sourceName: "Policy Forum",
    sourceRole: "媒体",
    sourceUrl: "https://example.com/source/model-policy-roundtable",
    author: "Forum Desk",
    publishedAt: "2026-07-18T09:00:00+08:00",
    discoveredAt: "2026-07-18T12:00:00+08:00",
    eventSlugs: ["open-model-license-policy"],
    primaryEventSlug: "open-model-license-policy",
    originalDisplay: "excerpt",
  },
  {
    slug: "model-license-legal-analysis",
    translatedTitle: "法律分析指出软件许可证难覆盖模型责任链",
    originalTitle: "Software licenses do not map cleanly onto model responsibility chains",
    summary: "训练与再分发产生新的权利边界",
    translatedContent: "分析认为，模型训练、微调和权重再分发形成的责任链无法直接套用传统软件许可证。",
    originalContent: "Training, fine-tuning and weight redistribution create a responsibility chain that conventional software licenses do not fully address.",
    originalLanguage: "en",
    sourceName: "Technology Law Review",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/model-license-law",
    author: "Legal Research Group",
    publishedAt: "2026-07-18T11:30:00+08:00",
    discoveredAt: "2026-07-18T12:00:00+08:00",
    eventSlugs: ["open-model-license-policy", "inference-price-update"],
    primaryEventSlug: "open-model-license-policy",
    originalDisplay: "excerpt",
  },
  {
    slug: "context-window-benchmark-update",
    translatedTitle: "长上下文评测新增跨文档引用错误指标",
    originalTitle: "Long-context benchmark adds cross-document citation errors",
    summary: "新指标开始区分检索与引用错误",
    translatedContent: "评测更新加入跨文档引用错误指标，用于区分模型没有找到信息和找到信息后错误归因两类失败。",
    originalContent: "The benchmark now separates retrieval failures from attribution errors after relevant evidence has already been found.",
    originalLanguage: "en",
    sourceName: "Benchmark Release",
    sourceRole: "研究",
    sourceUrl: "https://example.com/source/context-benchmark",
    author: "Evaluation Group",
    publishedAt: "2026-07-22T17:35:00+08:00",
    discoveredAt: "2026-07-22T18:00:00+08:00",
    eventSlugs: [],
    originalDisplay: "excerpt",
  },
  {
    slug: "local-agent-toolkit-release",
    translatedTitle: "本地 Agent 工具包发布最小权限执行模式",
    originalTitle: "Local agent toolkit ships a least-privilege execution mode",
    summary: "工具调用默认收紧文件与网络权限",
    translatedContent: "新模式默认关闭不必要的文件和网络访问，开发者需要为每类工具调用明确声明权限。",
    originalContent: "The new mode denies unnecessary file and network access by default and requires explicit permissions for each tool class.",
    originalLanguage: "en",
    sourceName: "GitHub Release",
    sourceRole: "官方",
    sourceUrl: "https://github.com/example/local-agent-toolkit",
    author: "Toolkit Maintainers",
    publishedAt: "2026-07-22T16:20:00+08:00",
    discoveredAt: "2026-07-22T18:00:00+08:00",
    eventSlugs: [],
    originalDisplay: "full",
  },
  {
    slug: "ai-workflow-podcast-note",
    translatedTitle: "播客讨论 AI 工作流中的人工确认边界",
    originalTitle: "Where human approval belongs in an AI workflow",
    summary: "高风险外部操作仍需要明确确认",
    translatedContent: "节目讨论付款、公开发布和删除数据等外部操作为何仍应保留明确的人工确认节点。",
    originalContent: "The episode argues that payments, public publishing and destructive data actions still require explicit human approval boundaries.",
    originalLanguage: "en",
    sourceName: "Practical AI Systems",
    sourceRole: "评论",
    sourceUrl: "https://example.com/source/human-approval-podcast",
    author: "Editorial Team",
    publishedAt: "2026-07-22T14:05:00+08:00",
    discoveredAt: "2026-07-22T18:00:00+08:00",
    eventSlugs: [],
    originalDisplay: "excerpt",
  },
  {
    slug: "compact-vision-model-test",
    translatedTitle: "独立测试比较紧凑视觉模型的界面理解能力",
    originalTitle: "Testing compact vision models on interface understanding",
    summary: "小模型在复杂界面状态中仍易漏读",
    translatedContent: "测试显示，紧凑视觉模型在简单表单中表现稳定，但在遮挡、弹窗和动态状态下仍容易漏读关键元素。",
    originalContent: "Compact vision models were reliable on simple forms but missed critical elements when interfaces contained overlays, dialogs or dynamic state.",
    originalLanguage: "en",
    sourceName: "Interface Bench",
    sourceRole: "测试",
    sourceUrl: "https://example.com/source/compact-vision-test",
    author: "UI Evaluation Lab",
    publishedAt: "2026-07-22T12:40:00+08:00",
    discoveredAt: "2026-07-22T18:00:00+08:00",
    eventSlugs: [],
    originalDisplay: "excerpt",
  },
];

export const services: Service[] = [
  { slug: "contract-review", code: "OPC/LEGAL/001", category: "法务", name: "单份标准商业合同审阅", price: "¥699", period: "3 个工作日", audience: "需要签署常见采购、服务或合作合同的一人公司。", includes: ["审阅一份不超过 20 页的中文合同", "标注主要风险与修改建议", "一次 30 分钟交付说明"], excludes: ["合同起草", "跨境交易", "诉讼或争议处理"], materials: ["可编辑合同文件", "交易背景说明", "期望达成的核心目标"], deliverables: ["修订标注版合同", "风险摘要"], revision: "REV.01" },
  { slug: "website-legal-pack", code: "OPC/LEGAL/002", category: "法务", name: "网站用户协议与隐私政策基础包", price: "¥1,999", period: "7 个工作日", audience: "面向中国大陆用户提供基础网络服务的早期产品。", includes: ["用户协议基础版本", "隐私政策基础版本", "一次业务信息访谈"], excludes: ["医疗、金融等强监管业务", "跨境数据专项评估", "定制交易条款"], materials: ["产品功能说明", "数据收集清单", "经营主体信息"], deliverables: ["用户协议", "隐私政策", "上线检查清单"], revision: "REV.01" },
  { slug: "tax-health-check", code: "OPC/TAX/001", category: "税务与财务", name: "经营主体税务健康检查", price: "¥899", period: "5 个工作日", audience: "已经开始经营，希望检查基础申报与票据风险的个体或公司。", includes: ["基础申报记录检查", "票据与收入匹配检查", "风险清单说明"], excludes: ["税务稽查代理", "历史账务重建", "专项税收筹划"], materials: ["主体基础信息", "近期申报表", "收入与票据汇总"], deliverables: ["税务健康检查报告", "整改事项清单"], revision: "REV.01" },
  { slug: "finance-consult", code: "OPC/TAX/002", category: "税务与财务", name: "一人公司基础财税咨询", price: "¥599", period: "60 分钟", audience: "正在选择经营主体或梳理日常财税流程的超级个体。", includes: ["一次线上咨询", "问题清单预审", "会后行动摘要"], excludes: ["出具正式鉴证意见", "代理申报", "复杂股权架构设计"], materials: ["背景说明", "拟咨询问题", "现有主体信息"], deliverables: ["咨询会议", "行动摘要"], revision: "REV.01" },
  { slug: "trademark-application", code: "OPC/IP/001", category: "知识产权", name: "单类别商标注册申请", price: "¥799 起", period: "以官方流程为准", audience: "需要为产品或品牌申请中国大陆商标的经营者。", includes: ["一个商标一个类别的基础检索", "材料整理", "申请提交"], excludes: ["驳回复审", "异议答辩", "复杂近似分析"], materials: ["申请主体材料", "商标图样或文字", "拟使用范围"], deliverables: ["申请材料", "官方受理文件"], revision: "REV.01" },
  { slug: "software-copyright", code: "OPC/IP/002", category: "知识产权", name: "软件著作权材料整理与申报", price: "¥1,499", period: "以官方流程为准", audience: "拥有可提交版本的软件产品或代码成果的一人公司。", includes: ["基础材料检查", "代码与说明书整理指引", "申请提交"], excludes: ["源代码代写", "权属争议处理", "加急官方费用"], materials: ["主体材料", "软件说明", "源代码样本"], deliverables: ["申报材料", "官方流程文件"], revision: "REV.01" },
  { slug: "icp-precheck", code: "OPC/FILING/001", category: "申报与备案", name: "ICP 备案材料预审", price: "¥499", period: "3 个工作日", audience: "准备在中国大陆服务器上线网站的经营主体。", includes: ["主体与域名材料检查", "网站信息检查", "提交前问题清单"], excludes: ["代替接入商提交", "许可证申请", "不符合政策业务整改"], materials: ["主体证件", "域名信息", "网站说明"], deliverables: ["材料预审结果", "补正清单"], revision: "REV.01" },
  { slug: "first-hire-pack", code: "OPC/HR/001", category: "人力资源", name: "首位员工入职文件包", price: "¥999", period: "5 个工作日", audience: "准备首次招聘全职员工的一人公司。", includes: ["劳动合同基础模板", "保密与知识产权条款", "入职材料清单"], excludes: ["高级管理人员激励", "劳务争议处理", "境外雇佣"], materials: ["主体信息", "岗位信息", "薪酬与试用期方案"], deliverables: ["入职文件包", "使用说明"], revision: "REV.01" },
  { slug: "founder-media-pack", code: "OPC/MEDIA/001", category: "传媒与传播", name: "创始人基础媒体资料包", price: "¥1,999", period: "7 个工作日", audience: "需要统一对外介绍产品、团队与创始人的早期项目。", includes: ["创始人简介", "产品标准介绍", "媒体问答基础版"], excludes: ["媒体投放", "舆情处置", "新闻稿代发"], materials: ["创始人与产品背景", "关键数据", "已有公开资料"], deliverables: ["媒体资料包", "版本维护清单"], revision: "REV.01" },
];

export const projects: TrendProject[] = [
  { owner: "northstar-labs", repo: "relay", rank: 1, change: "上升 4", category: "Agent", description: "为长任务提供可恢复状态与人工确认点的轻量运行时。", language: "TypeScript", stars: 12840, delta24: 684, delta7: 1922, license: "Apache-2.0", updated: "2 小时前", captured: "2026.07.21 14:00", fit: "适合需要把多步自动化交给 Agent，同时保留人工确认边界的一人公司。" },
  { owner: "carbon-stack", repo: "memoryline", rank: 2, change: "新入榜", category: "记忆", description: "可审计、可修订、可删除的 Agent 长期记忆层。", language: "Python", stars: 7621, delta24: 519, delta7: 1540, license: "MIT", updated: "4 小时前", captured: "2026.07.21 14:00", fit: "适合构建需要长期客户或项目上下文的个人工作系统。" },
  { owner: "open-workbench", repo: "mcp-audit", rank: 3, change: "下降 1", category: "MCP", description: "在安装前检查 MCP 服务权限、外部请求和密钥处理。", language: "Rust", stars: 19102, delta24: 430, delta7: 1318, license: "Apache-2.0", updated: "1 小时前", captured: "2026.07.21 14:00", fit: "适合经常试用外部工具连接、需要降低供应链风险的开发者。" },
  { owner: "small-models", repo: "routekit", rank: 4, change: "上升 7", category: "模型路由", description: "按成本、延迟和恢复率为不同任务选择模型。", language: "Python", stars: 5934, delta24: 388, delta7: 1014, license: "MIT", updated: "5 小时前", captured: "2026.07.21 14:00", fit: "适合模型调用已经形成稳定成本、需要精细控制毛利的 AI 产品。" },
  { owner: "silent-systems", repo: "briefcase", rank: 5, change: "保持", category: "Skill", description: "把重复业务流程封装为带输入边界和验收标准的 Skill。", language: "TypeScript", stars: 8430, delta24: 312, delta7: 989, license: "MIT", updated: "7 小时前", captured: "2026.07.21 14:00", fit: "适合已经拥有稳定清单，希望逐步把流程交给 Agent 的经营者。" },
  { owner: "voice-foundry", repo: "streamtalk", rank: 6, change: "下降 3", category: "语音", description: "端侧流式语音合成、打断检测与语义恢复组件。", language: "C++", stars: 24190, delta24: 277, delta7: 920, license: "Apache-2.0", updated: "3 小时前", captured: "2026.07.21 14:00", fit: "适合原型化实时语音助手或低延迟客服体验。" },
  { owner: "solo-ops", repo: "ledger", rank: 7, change: "上升 2", category: "自动化", description: "用事件账本连接客户、合同、发票和交付状态。", language: "Go", stars: 4420, delta24: 241, delta7: 802, license: "AGPL-3.0", updated: "6 小时前", captured: "2026.07.21 14:00", fit: "适合希望用一个可追溯系统替代多个松散表格的一人公司。" },
  { owner: "context-labs", repo: "handoff", rank: 8, change: "新入榜", category: "上下文", description: "在不同 Agent 和人工步骤之间传递最小必要上下文。", language: "TypeScript", stars: 3105, delta24: 219, delta7: 640, license: "MIT", updated: "2 小时前", captured: "2026.07.21 14:00", fit: "适合工具较多但信息经常在切换中丢失的个人工作流。" },
  { owner: "paperplane-ai", repo: "extractor", rank: 9, change: "下降 1", category: "数据", description: "从长文档提取带来源定位的结构化事实。", language: "Python", stars: 15602, delta24: 184, delta7: 588, license: "Apache-2.0", updated: "9 小时前", captured: "2026.07.21 14:00", fit: "适合需要把公告、合同或研究资料转为结构化记录的任务。" },
  { owner: "local-first-ai", repo: "cabinet", rank: 10, change: "上升 3", category: "知识库", description: "本地优先的个人与项目知识柜，支持明确的数据生命周期。", language: "Kotlin", stars: 9874, delta24: 162, delta7: 510, license: "MPL-2.0", updated: "11 小时前", captured: "2026.07.21 14:00", fit: "适合重视数据控制和离线可用性的长期知识工作。" },
  { owner: "metered-ai", repo: "margin", rank: 11, change: "下降 5", category: "成本", description: "按客户、任务和模型追踪推理成本与毛利。", language: "Go", stars: 7200, delta24: 140, delta7: 462, license: "MIT", updated: "12 小时前", captured: "2026.07.21 14:00", fit: "适合需要把模型成本落实到具体客户与工作流的产品。" },
  { owner: "plain-agents", repo: "humancheck", rank: 12, change: "保持", category: "Agent", description: "为高风险工具调用加入可配置的人工确认契约。", language: "TypeScript", stars: 5328, delta24: 126, delta7: 401, license: "MIT", updated: "8 小时前", captured: "2026.07.21 14:00", fit: "适合自动化已触及付款、发布或删除等外部操作的团队。" },
];

export const frontierEntries: FrontierEntry[] = [
  { rank: 1, repo: "northstar-labs/relay", description: "可恢复的长任务 Agent 运行时", baseline: 10122, current: 12840, delta: 2718, submitted: "2026.07.02" },
  { rank: 2, repo: "carbon-stack/memoryline", description: "可审计的长期记忆层", baseline: 5220, current: 7621, delta: 2401, submitted: "2026.07.04" },
  { rank: 3, repo: "open-workbench/mcp-audit", description: "MCP 服务安全审计工具", baseline: 16988, current: 19102, delta: 2114, submitted: "2026.07.01" },
  { rank: 4, repo: "small-models/routekit", description: "成本感知的模型路由", baseline: 4078, current: 5934, delta: 1856, submitted: "2026.07.06" },
  { rank: 5, repo: "silent-systems/briefcase", description: "业务流程 Skill 封装工具", baseline: 6950, current: 8430, delta: 1480, submitted: "2026.07.03" },
  { rank: 6, repo: "solo-ops/ledger", description: "一人公司事件账本", baseline: 3204, current: 4420, delta: 1216, submitted: "2026.07.08" },
  { rank: 7, repo: "context-labs/handoff", description: "Agent 间最小上下文传递", baseline: 2102, current: 3105, delta: 1003, submitted: "2026.07.11" },
  { rank: 8, repo: "paperplane-ai/extractor", description: "带来源定位的事实提取", baseline: 14880, current: 15602, delta: 722, submitted: "2026.07.09" },
];

export const prizes = ["端侧 AI 工作站一台", "年度云算力额度", "开源项目法律体检", "品牌与媒体资料包", "开发者工具年度订阅", "专业录音设备"];

export const historicalWinners = [
  { season: "2026 春季", repo: "field-notes/atlas", rank: 1, prize: "端侧 AI 工作站" },
  { season: "2026 春季", repo: "micro-studio/queue", rank: 2, prize: "年度云算力额度" },
  { season: "2026 春季", repo: "open-contracts/plain", rank: 3, prize: "开源项目法律体检" },
  { season: "2025 冬季", repo: "one-person-os/logbook", rank: 1, prize: "开发者工具年度订阅" },
];

export function formatNumber(value: number) {
  return new Intl.NumberFormat("zh-CN").format(value);
}
